# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import *
import os
import cv2
import numpy as np
from PyQt5 import uic

path = "./sample_imgs/"

"""
    filelist = os.listdir(path)
    
    for idx in range(0, len(filelist)):
    images = cv2.imread(path + filelist[idx], cv2.IMREAD_COLOR)
    images = cv2.resize(images, dsize=(150, 200))
    cv2.imwrite("images_{0}.jpg".format(idx), images)
    print(np.shape(images))
    cv2.imshow('images', images)
    cv2.waitKey(0)
"""

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 514)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)

        # 전체 vertical layout
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.v_whole_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.v_whole_layout.setContentsMargins(0, 0, 0, 0)
        self.v_whole_layout.setObjectName("v_whole_layout")

        # 첫번째 horizontal layout
        self.h_1_layout = QtWidgets.QHBoxLayout()
        self.h_1_layout.setObjectName("h_1_layout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.h_1_layout.addItem(spacerItem)
        self.h_1_textlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.h_1_textlabel.setObjectName("h_1_textlabel")
        self.h_1_layout.addWidget(self.h_1_textlabel)
        self.h_1_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.h_1_button.sizePolicy().hasHeightForWidth())
        self.h_1_button.setSizePolicy(sizePolicy)
        self.h_1_button.setCheckable(False)
        self.h_1_button.setObjectName("h_1_button")
        self.h_1_layout.addWidget(self.h_1_button)
        spacerItem1 = QtWidgets.QSpacerItem(100, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.h_1_layout.addItem(spacerItem1)
        self.v_whole_layout.addLayout(self.h_1_layout)

        self.h_1_button.clicked.connect(self.numbering)

        # 두번째 horizontal layout
        self.h_2_layout = QtWidgets.QHBoxLayout()
        self.h_2_layout.setObjectName("h_2_layout")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.h_2_layout.addItem(spacerItem2)
        self.h_2_textlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.h_2_textlabel.setObjectName("h_2_textlabel")
        self.h_2_layout.addWidget(self.h_2_textlabel)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.h_2_layout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.h_2_layout.addItem(spacerItem3)
        self.v_whole_layout.addLayout(self.h_2_layout)

        self.pushButton.clicked.connect(self.fibonacci)

        # 세번째 horizontal layout
        self.h_3_layout = QtWidgets.QHBoxLayout()
        self.h_3_layout.setObjectName("h_3_layout")
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.h_3_layout.addItem(spacerItem4)
        self.h_3_textlabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.h_3_textlabel.setObjectName("h_3_textlabel")
        self.h_3_layout.addWidget(self.h_3_textlabel)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.h_3_layout.addWidget(self.pushButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.h_3_layout.addItem(spacerItem5)
        self.v_whole_layout.addLayout(self.h_3_layout)


        filelist = os.listdir(path)
        for idx in range(0, len(filelist)):
            images = cv2.imread(path + filelist[idx], cv2.IMREAD_COLOR)
        print(type(images))
        self.h_3_textlabel.setPixmap(images)
        self.pushButton_2.clicked.connect(self.image_load)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.h_1_textlabel.setText(_translate("Dialog", "0"))
        self.h_1_button.setText(_translate("Dialog", "+1"))
        self.h_2_textlabel.setText(_translate("Dialog", "0"))
        self.pushButton.setText(_translate("Dialog", "피보나치"))
        self.h_3_textlabel.setText(_translate("Dialog", "Image"))
        self.pushButton_2.setText(_translate("Dialog", "이미지 바꾸기"))

    number = 0
    def numbering(self):
        self.number += 1
        self.h_1_textlabel.setText(str(self.number))

    a, b = 0, 1
    def fibonacci(self):
        self.a, self.b = self.b, self.a+self.b
        self.h_2_textlabel.setText((str(self.a)))

    idx = 0
    def image_load(self):
        self.idx+=1



        if(self.idx == 10):
            self.idx == 0


if __name__ == "__main__":
    import sys
    print(path+"images_{0}.png".format(0))
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

    Dialog.show()
    sys.exit(app.exec_())
